import './app.js';
import { findProduct, formatPrice } from './products.js';
import { getCart, removeFromCart, updateCart } from './store.js';

const root = document.querySelector('[data-cart-page]');
function render() {
  const items = getCart().map((entry) => ({ ...entry, product: findProduct(entry.id) })).filter((entry) => entry.product);
  if (!items.length) { root.innerHTML = '<div class="empty-state"><div class="empty-icon">◇</div><h2>Your bag is empty.</h2><p>Explore the collection and discover a scent made for you.</p><a class="button button-dark" href="arrival.html">Continue shopping</a></div>'; return; }
  const subtotal = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0); const shipping = subtotal >= 999 ? 0 : 99;
  root.innerHTML = `<div class="cart-layout"><div>${items.map(({ product, quantity }) => `<article class="cart-item"><a class="cart-item-image" href="product.html?id=${product.id}"><img src="${product.image}" alt="${product.name}"></a><div><h2><a href="product.html?id=${product.id}">${product.name}</a></h2><p>${product.category} · ${product.size}</p><div class="quantity"><button data-cart-minus="${product.id}" aria-label="Decrease ${product.name} quantity">−</button><input value="${quantity}" readonly aria-label="Quantity"><button data-cart-plus="${product.id}" aria-label="Increase ${product.name} quantity">+</button></div><button class="remove-button" data-remove="${product.id}">Remove</button></div><strong>${formatPrice(product.price * quantity)}</strong></article>`).join('')}</div><aside class="order-summary"><p class="eyebrow">Order summary</p><h2>Your total</h2><div class="summary-row"><span>Subtotal</span><span>${formatPrice(subtotal)}</span></div><div class="summary-row"><span>Shipping</span><span>${shipping ? formatPrice(shipping) : 'Complimentary'}</span></div><div class="summary-row"><span>Discount</span><span>—</span></div><div class="summary-row summary-total"><span>Total</span><span>${formatPrice(subtotal + shipping)}</span></div><button class="button button-dark" data-checkout>Proceed to checkout</button><p class="checkout-note">Demonstration store — no payment will be processed.</p><div class="form-status" data-checkout-status aria-live="polite"></div></aside></div>`;
}
root.addEventListener('click', (event) => { const plus = event.target.closest('[data-cart-plus]'); const minus = event.target.closest('[data-cart-minus]'); const remove = event.target.closest('[data-remove]'); if (plus) { const item = getCart().find((entry) => entry.id === Number(plus.dataset.cartPlus)); updateCart(item.id, item.quantity + 1); } if (minus) { const item = getCart().find((entry) => entry.id === Number(minus.dataset.cartMinus)); updateCart(item.id, item.quantity - 1); } if (remove) removeFromCart(remove.dataset.remove); if (event.target.closest('[data-checkout]')) document.querySelector('[data-checkout-status]').textContent = 'Checkout is in demonstration mode. No payment has been processed.'; });
window.addEventListener('srk:state', render); render();
